### ISSUE TITLE
能否让个人部署一个loveliveplayer网页服务端+流媒体？

### ISSUE THREAD

**Issue by onecreeper** [zhushenwudi/LoveLiveMusicPlayer#1]
# 需求
如题，虽然http共享解决了很多问题，但外网环境，手机访问时，电脑一直开机不是一件好事。希望能有一个docker项目用nas搭建一个网络音乐服务，我尝试过用其他流媒体服务搭建，但由于不是lovelive专用的，无法很好区分团，而歌手命名格式有点混乱，有时不一定能找到自己想听的歌。

## 简单实现
我记得http功能是别人来帮忙的吧(？)可能docker会有点难(?)
其实也不用那么麻烦，需求可以简化成在nas上运行一个没有giu的loveliveplayer只有http服务或其他流媒体服务，配合未来的手机端，感谢。

**Comment by zhushenwudi** [comment]
在远端服务器搭建一个http-server即可，LLMP本身也是启动的这个服务
